version: "3.8"

services: 
  postgres: 
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=ec2-3-223-242-224.compute-1.amazonaws.com
      - POSTGRES_USER=lbhlbtssvkwovq
      - POSTGRES_PASSWORD=cc226e49b82bc7bdabb751a034693cc7470f297a50602c68e7c9ff5cc3c8456a
      - POSTGRES_DB=d2a0k1v7glbdm4
  
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "thmpv77d6f"
    ports: 
      - "81:80"
    depends_on: 
      - postgres

      
